#!/usr/bin/env bash
#
# surface-protect.sh - Blocks manual edits to generated files
#
# This hook runs on PreToolUse for Edit|Write operations.
# It prevents direct edits to files that should only be generated by tools.
#
# Exit codes:
#   0 = allow (file is not protected)
#   2 = deny (file is protected, edit blocked)

# Drain stdin (hook receives JSON input we don't need)
cat > /dev/null

set -euo pipefail

# Protected files - these should only be generated, never manually edited
PROTECTED_FILES=(
  "surface.json"
  "SURFACE.md"
  "docs/features/"    # Generated feature docs
)

# Get the file path from CLAUDE_FILE_PATH
FILE_PATH="${CLAUDE_FILE_PATH:-}"

if [[ -z "$FILE_PATH" ]]; then
  # No file path provided, allow the operation
  exit 0
fi

# Output deny JSON and exit with code 2
deny_edit() {
  cat << EOF
{
  "decision": "deny",
  "reason": "Cannot manually edit generated file: $FILE_PATH. This file is auto-generated by Surface Protocol. Run 'surface gen' to regenerate."
}
EOF
  exit 2
}

# Check if the file matches any protected pattern
# Patterns ending in "/" are directory prefixes; others are exact filename matches
for pattern in "${PROTECTED_FILES[@]}"; do
  case "$pattern" in
    */)
      # Directory prefix match
      case "$FILE_PATH" in
        "$pattern"*)
          deny_edit
          ;;
      esac
      ;;
    *)
      # Exact filename match
      if [[ "$FILE_PATH" == "$pattern" ]]; then
        deny_edit
      fi
      ;;
  esac
done

# File is not protected, allow the operation
exit 0
